
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QUrl
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 900)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_v1 = QtWebEngineWidgets.QWebEngineView(parent=self.centralwidget)
        self.widget_v1.setGeometry(QtCore.QRect(0, 0, 450, 450))
        self.widget_v1.setObjectName("widget_v1")
        # base_dir = os.path.dirname(os.path.abspath(__file__))
        # html_path = os.path.join(base_dir, "G.html")
        html_path = "U:\GitHubDesktopData\BA-Sauerteig\G.html"
        self.widget_v1.load(QUrl.fromLocalFile(html_path))
        self.widget_v2 = QtWebEngineWidgets.QWebEngineView(parent=self.centralwidget)
        self.widget_v2.setGeometry(QtCore.QRect(450, 0, 450, 450))
        self.widget_v2.setBaseSize(QtCore.QSize(450, 450))
        self.widget_v2.setObjectName("widget_v2")
        self.widget_v2.load(QUrl.fromLocalFile(html_path))
        self.line_2 = QtWidgets.QFrame(parent=self.widget_v2)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 5, 450))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 450, 900, 5))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 450, 900, 450))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(450, 0, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(parent=self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menu_ffnen = QtWidgets.QMenu(parent=self.menuDatei)
        self.menu_ffnen.setObjectName("menu_ffnen")
        self.menuSclie_en = QtWidgets.QMenu(parent=self.menubar)
        self.menuSclie_en.setObjectName("menuSclie_en")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAus_Datei = QtGui.QAction(parent=MainWindow)
        self.actionAus_Datei.setObjectName("actionAus_Datei")
        self.actionLetzte = QtGui.QAction(parent=MainWindow)
        self.actionLetzte.setObjectName("actionLetzte")
        self.menu_ffnen.addAction(self.actionAus_Datei)
        self.menu_ffnen.addAction(self.actionLetzte)
        self.menuDatei.addAction(self.menu_ffnen.menuAction())
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuSclie_en.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hive Plot Manager"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.label_2.setText(_translate("MainWindow", "Variable Position"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menu_ffnen.setTitle(_translate("MainWindow", "Öffnen..."))
        self.menuSclie_en.setTitle(_translate("MainWindow", "Schließen"))
        self.actionAus_Datei.setText(_translate("MainWindow", "aus Datei"))
        self.actionLetzte.setText(_translate("MainWindow", "Letzte"))
from PyQt6 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())